blank_issues_enabled: false
contact_links:
  - name: 👥 Discussions
    url:  https://github.com/Bmanjali/DWX-2023
    about: Please use discussions for issues that are not a bug, enhancement or feature request
