name: 'Hallo World Action'
description: 'Steh mal auf, Digger!'
inputs: 
  who-to-trigger:
    description: 'Wen willst du dazu auffordern?'
    required: true
    default: 'Alle'
outputs:
  time: 
    description: 'Wann wurde dazu aufgefordert?'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-trigger }}
